const ShopActionTypes={
    FETCH_COLLECTION_START:'FETCH_COLLECTION_START',
    FETCH_COLLECTION_SUCCESS:'FETCH_COLLECTION_SUCCESS',
    FETCH_COLLOECTION_FAILURE:'FETCH_COLLOECTION_FAILURE'
}

export default ShopActionTypes;